server:
  port: 7070
  servlet:
    context-path: /xshop
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xshop
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  thymeleaf:
    cache: false
    mode: LEGACYHTML5




